### ISSUE TITLE
Not working under FF Beta 128.0b3 and FF Developer Editon 128.0b3

### ISSUE THREAD

**Issue by Icepenguins101** [MrOtherGuy/fx-autoconfig#52]
Trying this under macOS Sonoma 14.5, for some reason Firefox Beta and Developer Edition does not load up userchrome js repositories despite working in the main branch (127.0.1) and Firefox Nightly (129.0a1).

**Comment by MrOtherGuy** [comment]
> Apparently there's a flaw with the 128.0b3 upgrade that deletes most of the files for that folder.

Do you have a bug id to share?

**Comment by Icepenguins101** [comment]
> > Apparently there's a flaw with the 128.0b3 upgrade that deletes most of the files for that folder.
> 
> Do you have a bug id to share?

No. It seems to have been fixed in 128.0b4.

**Comment by MrOtherGuy** [comment]
Alright. I suppose it's good to have this issue still listed as open in case someone else stumbles into it. I'd kinda like to know what could have caused that kind of thing though.
